<?php

/**
 * @file
 */

use Drupal\Core\Database\Database;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_delete().
 * @throws Exception
 */
function argo_entity_delete(EntityInterface $entity) {
  $conn = Database::getConnection();
  $conn->insert('argo_entity_deletion')
    ->fields([
      'entityType' => $entity->getEntityTypeId(),
      'bundle' => $entity->bundle(),
      'uuid' => $entity->uuid(),
    ])->execute();
}
