<?php

/**
 * @file
 * Implement hook for Argo module.
 */

use Drupal\Core\Database\Database;
use Drupal\Core\Entity\EntityInterface;
use Psr\Log\LogLevel;

/**
 * Implements hook_entity_delete().
 *
 * @throws Exception
 */
function argo_entity_delete(EntityInterface $entity) {
  $conn = Database::getConnection();
  try {
    $conn->upsert('argo_entity_deletion')
      ->fields([
        'entityType' => $entity->getEntityTypeId(),
        'bundle' => $entity->bundle(),
        'uuid' => $entity->uuid(),
      ])->execute();
  } catch (Exception $e) {
    \Drupal::logger('argo')->log(LogLevel::ERROR, 'Failed to log entity deletion to Argo');
    throw $e;
  }
}
